# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Pour l'inclusion, la compréhension, l'acceptation et la réussite des personnes sur le spectre de l'autisme
email: 
lang: fr
description: > # this means to ignore newlines until "baseurl:"
  Faire comprendre ce qu'est l'autisme au grand public et construire une société inclusive.
#  Faire que le grand public comprenne réellement ce qu'est l'autisme et construire une société inclusive.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://autisme.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: BastienBConfais
#github_username:  autisme
google_verify: mpUcls0ghJHiock1KTv2d00nVpzQI82SZGDo1nsaziU
google_analytics: UA-99588632-1
bing_verify: 10AC9E0EFAD518AB76B218E4121A15B5
permalink: /:title

# Build settings
markdown: kramdown
#theme: minima
gems:
  - jekyll-feed
  - jekyll-sitemap
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
